/**
 * GhostNote Universal Language Engine
 * 10 Core Languages with UI Translations
 * Professional/Executive Grade
 */

export const LANGUAGES = [
    { code: 'EN', name: 'English', native: 'English' },
    { code: 'FR', name: 'French', native: 'Français' },
    { code: 'ES', name: 'Spanish', native: 'Español' },
    { code: 'ZH', name: 'Chinese', native: '中文' },
    { code: 'RU', name: 'Russian', native: 'Русский' },
    { code: 'DE', name: 'German', native: 'Deutsch' },
    { code: 'JA', name: 'Japanese', native: '日本語' },
    { code: 'PT', name: 'Portuguese', native: 'Português' },
    { code: 'AR', name: 'Arabic', native: 'العربية' },
    { code: 'HI', name: 'Hindi', native: 'हिन्दी' },
];

export const getLanguageName = (code) => {
    const lang = LANGUAGES.find(l => l.code === code);
    return lang ? lang.name : 'English';
};

export const TRANSLATIONS = {
    EN: {
        hero: {
            title: "Turn Chaos Into ",
            titleHighlight: "Strategy.",
            subtitle: "The private engine to transmute executive voice notes into a strategic suite.",
            footer: "No typing. No hallucinations. Just your intent, crystallized.",
        },
        navigation: {
            drafts: "DRAFTS",
            history: "HISTORY",
            new: "NEW SESSION",
            signin: "SIGN IN"
        },
        buttons: {
            record: "Record",
            upload: "Upload",
            transmute: "Transmute my thoughts",
            save_draft: "Save Draft",
            discard: "Discard",
            rerecord: "Re-record",
            remove: "Remove",
            copy: "COPY",
            share: "SHARE",
            email: "EMAIL THIS",
            regenerate: "REGENERATE",
            gift: "GIFT GHOSTNOTE PRO",
            upgrade: "UPGRADE TO PRO",
            select_file: "Select audio file",
            edit: "Edit Transcription",
            save_generate: "Save & Generate",
        },
        scribe: {
            title: "THE SCRIBE",
            description: "Your raw thoughts, crystallized into a Wall Street Journal caliber thesis.",
            core_thesis: "CORE THESIS",
            strategic_pillars: "STRATEGIC PILLARS",
            transcription: "TRANSCRIPTION",
            tactical_steps: "TACTICAL STEPS"
        },
        strategist: {
            title: "THE STRATEGIST",
            description: "AI Chief of Staff intelligence. Judgment. Risk Audits. Execution-ready emails.",
            judgment: "EXECUTIVE JUDGMENT",
            risk_audit: "RISK AUDIT",
            email_draft: "EMAIL DRAFT",
            unlock_title: "Unlock The Strategist",
            unlock_desc: "Get the full Chief of Staff suite: Executive Judgment, Risk Audits, and ready-to-send Emails.",
            operationalize: "OPERATIONALIZE THIS STRATEGY"
        },
        status: {
            reflective: "REFLECTIVE",
            decisive: "DECISIVE",
            analytical: "ANALYTICAL",
            urgent: "URGENT",
            strategic: "STRATEGIC",
            operational: "OPERATIONAL",
            low: "LOW INTENSITY",
            medium: "MEDIUM INTENSITY",
            high: "HIGH INTENSITY"
        },
        messages: {
            processing: "TRANSMUTING...",
            uploading: "Uploading audio...",
            transcribing: "Transcribing voice...",
            extracting: "Extracting core insights...",
            formatting: "Formatting final strategy...",
            mic_error: "Microphone access required.",
            draft_saved: "Saved to Drafts!",
            copy_success: "Link copied to clipboard",
            share_text: "I'm using GhostNote Pro to transmute my thoughts. Try it here:",
            ready: "Ready to turn noise into signal.",
            tap_record: "Tap to Record",
            tap_finish: "Tap to Finish",
            free_limit: "Free transmutations complete. Upgrade to Pro",
            powered_by: "Powered by GhostNote Pro",
            generated_on: "Generated on",
            create_own: "Create Your Own Strategic Brief",
            archive_success: "Strategic brief archived. Link copied.",
            archive_fail: "Failed to archive."
        },
        legal: {
            privacy: "Privacy",
            terms: "Terms",
            refund: "Refund Policy"
        },
        modes: {
            record_desc: "Capture your strategic thoughts via voice recording.",
            upload_desc: "Upload an existing audio file for analysis."
        },
        labels: {
            duration: "Duration",
            intensity: "Intensity",
            executive_state: "Executive State",
            emphasis_audit: "Emphasis Audit",
            generate_suite: "GENERATE EXECUTIVE SUITE",
            archive_share: "Archive & Share Brief",
            exec_status: "Executive Status",
            pro: "Pro",
            standard: "Standard",
            new_session: "New Session"
        },
        wager: {
            lock_title: "Judgment Lock",
            lock_desc: "Don't just hope. Predict. Lock this decision into 'History' to test your judgment accuracy later.",
            seal_btn: "Seal Time Capsule",
            prediction_lbl: "The Prediction",
            prediction_placeholder: "What is the expected outcome in reality?",
            timeline_lbl: "Audit Timeline",
            confirm_btn: "Confirm Judgment Lock",
            cancel_btn: "Cancel",
            sealing: "Sealing...",
            success: "Time Capsule Sealed. Judgment locked.",
            fail: "Failed to seal time capsule."
        },
        drafts_view: {
            subtitle: "Raw ideas. Unhatched plans. Dump your brain here.",
            empty_title: "No drafts yet",
            empty_desc: "Record a thought and hit 'Save Draft' to save it here."
        },
        history_view: {
            title: "History",
            subtitle: "Judgment Variance Engine",
            no_wagers: "NO WAGERS FOUND",
            quote: "\"The unexamined decision is not worth making.\"",
            avg_accuracy: "Avg Accuracy",
            total_wagers: "Total Wagers",
            blind_spot: "Blind Spot",
            insight: "Insight",
            reckoning_title: "The Reckoning",
            reckoning_desc: "Record what actually happened. Gemini will calculate the variance.",
            record_update: "Record Update",
            update_captured: "Update Captured.",
            seal_judgment: "Seal Judgment",
            running: "Running Variance Engine...",
            discard: "Discard and Re-record",
            return: "Return to History",
            accuracy_score: "Judgment Accuracy Score"
        },
        brief_view: {
            retrieving: "Retrieving from Vault...",
            not_found: "Archive Not Found",
            expunged: "This strategic brief has been expunged or never existed.",
            return_command: "Return to Command",
            archive_label: "GhostNote Pro Archive",
            create_own: "Create Your Own Brief",
            duration: "DURATION",
            intensity: "INTENSITY",
            state: "State",
            generated_by: "This strategic brief was generated by GhostNote Pro."
        },
        museum: {
            header_reader: "READER",
            try_free: "Try Free",
            memo_label: "Strategic Memo",
            internal_access: "Internal Access Only",
            encrypted: "Encrypted Intelligence",
            lock_title: "Executive Risk Audit & Private Drafts",
            lock_desc: "This intelligence is private to the author. Generate your own strategic suite to unlock risk auditors and execution assets.",
            built_for: "Built for the modern executive.",
            opening: "Opening the archives..."
        },
        paywall: {
            headline: "Continue turning thought into strategy",
            subtext: "Pro removes daily limits and unlocks executive-grade transmutation, confidence analysis, and shareable outputs.",
            cancel: "Cancel anytime. No hidden fees.",
            restore: "Restore Purchase",
            button_usd: "Continue with Membership — $20/month",
            button_ngn: "Continue with Membership — ₦30,000/month",
            payment_error: "Payment system is temporarily unavailable. Please try again.",
            verification_failed: "Verification Failed",
            network_error: "Verification failed due to network error.",
            gateway_error: "Could not open payment gateway. Please refresh."
        }
    },
    FR: {
        hero: {
            title: "Transformez le Chaos en ",
            titleHighlight: "Stratégie.",
            subtitle: "Le moteur privé pour transmuter les notes vocales exécutives en suite stratégique.",
            footer: "Pas de saisie. Pas d'allucinations. Juste votre intention, cristallisée.",
        },
        navigation: {
            drafts: "BROUILLONS",
            history: "HISTORIQUE",
            new: "NOUVELLE SESSION",
            signin: "CONNEXION"
        },
        buttons: {
            record: "Enregistrer",
            upload: "Télécharger",
            transmute: "Transmuter mes pensées",
            save_draft: "Sauvegarder",
            discard: "Jeter",
            rerecord: "Réenregistrer",
            remove: "Supprimer",
            copy: "COPIER",
            share: "PARTAGER",
            email: "ENVOYER PAR EMAIL",
            regenerate: "RÉGÉNÉRER",
            gift: "OFFRIR GHOSTNOTE PRO",
            upgrade: "PASSER À PRO",
            select_file: "Sélectionner un fichier",
        },
        scribe: {
            title: "LE SCRIBE",
            description: "Vos pensées brutes, cristallisées en une thèse du calibre du Wall Street Journal.",
            core_thesis: "THÈSE CENTRALE",
            strategic_pillars: "PILIERS STRATÉGIQUES",
            transcription: "TRANSCRIPTION",
            tactical_steps: "ÉTAPES TACTIQUES"
        },
        strategist: {
            title: "LE STRATÈGE",
            description: "Intelligence Chef de Cabinet IA. Jugement. Audits de Risques. Emails prêts à l'exécution.",
            judgment: "JUGEMENT EXÉCUTIF",
            risk_audit: "AUDIT DE RISQUE",
            email_draft: "PROJET D'EMAIL",
            unlock_title: "Débloquer Le Stratège",
            unlock_desc: "Obtenez la suite complète du Chef de Cabinet : Jugement Exécutif, Audits de Risques et Emails prêts à l'envoi.",
            operationalize: "OPÉRATIONNALISER CETTE STRATÉGIE"
        },
        status: {
            reflective: "RÉFLEXIF",
            decisive: "DÉCISIF",
            analytical: "ANALYTIQUE",
            urgent: "URGENT",
            strategic: "STRATÉGIQUE",
            operational: "OPÉRATIONNEL",
            low: "INTENSITÉ FAIBLE",
            medium: "INTENSITÉ MOYENNE",
            high: "INTENSITÉ ÉLEVÉE"
        },
        messages: {
            processing: "TRANSMUTATION...",
            uploading: "Téléchargement de l'audio...",
            transcribing: "Transcription de la voix...",
            extracting: "Extraction des informations clés...",
            formatting: "Mise en forme de la stratégie...",
            mic_error: "Accès au microphone requis.",
            draft_saved: "Enregistré dans les brouillons !",
            copy_success: "Lien copié dans le presse-papiers",
            share_text: "J'utilise GhostNote Pro pour transmuter mes pensées. Essayez-le ici :",
            ready: "Prêt à transformer le bruit en signal.",
            tap_record: "Appuyez pour enregistrer",
            tap_finish: "Appuyez pour terminer",
            free_limit: "Transmutations gratuites terminées. Passez à Pro",
            powered_by: "Propulsé par GhostNote Pro",
            generated_on: "Généré le",
            create_own: "Créez votre propre brief stratégique",
            archive_success: "Brief stratégique archivé. Lien copié.",
            archive_fail: "Échec de l'archivage."
        },
        legal: {
            privacy: "Confidentialité",
            terms: "Conditions",
            refund: "Politique de remboursement"
        },
        modes: {
            record_desc: "Capturez vos pensées stratégiques via l'enregistrement vocal.",
            upload_desc: "Téléchargez un fichier audio existant pour analyse."
        },
        labels: {
            duration: "Durée",
            intensity: "Intensité",
            executive_state: "État Exécutif",
            emphasis_audit: "Audit d'Emphase",
            generate_suite: "GÉNÉRER SUITE EXÉCUTIVE",
            archive_share: "Archiver et Partager",
            exec_status: "Statut Exécutif",
            pro: "Pro",
            standard: "Standard",
            new_session: "Nouvelle Session"
        },
        wager: {
            lock_title: "Verrouillage du Jugement",
            lock_desc: "Ne vous contentez pas d'espérer. Prédisez. Verrouillez cette décision dans l'Historique pour tester la précision de votre jugement plus tard.",
            seal_btn: "Sceller la Capsule Temporelle",
            prediction_lbl: "La Prédiction",
            prediction_placeholder: "Quel est le résultat attendu dans la réalité ?",
            timeline_lbl: "Calendrier d'Audit",
            confirm_btn: "Confirmer le Verrouillage",
            cancel_btn: "Annuler",
            sealing: "Scellage...",
            success: "Capsule Scellée. Jugement verrouillé.",
            fail: "Échec du scellage de la capsule."
        },
        drafts_view: {
            subtitle: "Idées brutes. Plans non éclos. Déposez votre cerveau ici.",
            empty_title: "Pas encore de brouillons",
            empty_desc: "Enregistrez une pensée et cliquez sur 'Sauvegarder' pour la stocker ici."
        },
        history_view: {
            title: "Historique",
            subtitle: "Moteur de Variance du Jugement",
            no_wagers: "AUCUN PARI TROUVÉ",
            quote: "\"Une vie sans examen ne vaut pas la peine d'être vécue.\"",
            avg_accuracy: "Précision Moyenne",
            total_wagers: "Total des Paris",
            blind_spot: "Angle Mort",
            insight: "Insight",
            reckoning_title: "Le Règlement de Comptes",
            reckoning_desc: "Enregistrez ce qui s'est réellement passé. Gemini calculera la variance.",
            record_update: "Enregistrer Mise à Jour",
            update_captured: "Mise à jour capturée.",
            seal_judgment: "Sceller le Jugement",
            running: "Exécution du Moteur de Variance...",
            discard: "Jeter et Réenregistrer",
            return: "Retour à l'Historique",
            accuracy_score: "Score de Précision du Jugement"
        },
        brief_view: {
            retrieving: "Récupération du Coffre...",
            not_found: "Archive Non Trouvée",
            expunged: "Ce brief stratégique a été supprimé ou n'a jamais existé.",
            return_command: "Retour au Commandement",
            archive_label: "Archive GhostNote Pro",
            create_own: "Créez votre propre brief",
            duration: "DURÉE",
            intensity: "INTENSITÉ",
            state: "État",
            generated_by: "Ce brief stratégique a été généré par GhostNote Pro."
        },
        museum: {
            header_reader: "LECTEUR",
            try_free: "Essayer Gratuitement",
            memo_label: "Mémo Stratégique",
            internal_access: "Accès Interne Uniquement",
            encrypted: "Intelligence Chiffrée",
            lock_title: "Audit de Risque Exécutif & Brouillons Privés",
            lock_desc: "Cette intelligence est privée à l'auteur. Générez votre propre suite stratégique pour débloquer les auditeurs de risques et les actifs d'exécution.",
            built_for: "Conçu pour l'exécutif moderne.",
            opening: "Ouverture des archives..."
        },
        paywall: {
            headline: "Continuez à transformer la pensée en stratégie",
            subtext: "Pro supprime les limites quotidiennes et débloque la transmutation de niveau exécutif, l'analyse de confiance et les sorties partageables.",
            cancel: "Annulez à tout moment. Pas de frais cachés.",
            restore: "Restaurer l'achat",
            button_usd: "Continuer l'adhésion — 20 $/mois",
            button_ngn: "Continuer l'adhésion — 30 000 ₦/mois",
            payment_error: "Le système de paiement est temporairement indisponible. Veuillez réessayer.",
            verification_failed: "Échec de la vérification",
            network_error: "La vérification a échoué en raison d'une erreur réseau.",
            gateway_error: "Impossible d'ouvrir la passerelle de paiement. Veuillez actualiser."
        }
    },
    ES: {
        hero: {
            title: "Convierta el Caos en ",
            titleHighlight: "Estrategia.",
            subtitle: "El motor privado para transmutar notas de voz ejecutivas en una suite estratégica.",
            footer: "Sin escribir. Sin alucinaciones. Solo su intención, cristalizada.",
        },
        navigation: {
            drafts: "BORRADORES",
            history: "HISTORIAL",
            new: "NUEVA SESIÓN",
            signin: "INICIAR SESIÓN"
        },
        buttons: {
            record: "Grabar",
            upload: "Subir",
            transmute: "Transmutar mis pensamientos",
            save_draft: "Guardar",
            discard: "Descartar",
            rerecord: "Regrabar",
            remove: "Eliminar",
            copy: "COPIAR",
            share: "COMPARTIR",
            email: "ENVIAR POR EMAIL",
            regenerate: "REGENERAR",
            gift: "REGALAR GHOSTNOTE PRO",
            upgrade: "MEJORAR A PRO",
            select_file: "Seleccionar archivo",
        },
        scribe: {
            title: "EL ESCRIBA",
            description: "Sus pensamientos crudos, cristalizados en una tesis del calibre del Wall Street Journal.",
            core_thesis: "TESIS CENTRAL",
            strategic_pillars: "PILARES ESTRATÉGICOS",
            transcription: "TRANSCRIPCIÓN",
            tactical_steps: "PASOS TÁCTICOS"
        },
        strategist: {
            title: "EL ESTRATEGA",
            description: "Inteligencia de Jefe de Gabinete IA. Juicio. Auditorías de Riesgo. Correos listos para ejecutar.",
            judgment: "JUICIO EJECUTIVO",
            risk_audit: "AUDITORÍA DE RIESGOS",
            email_draft: "BORRADOR DE CORREO",
            unlock_title: "Desbloquear El Estratega",
            unlock_desc: "Obtenga la suite completa de Jefe de Gabinete: Juicio Ejecutivo, Auditorías de Riesgo y Correos listos para enviar.",
            operationalize: "OPERACIONALIZAR ESTA ESTRATEGIA"
        },
        status: {
            reflective: "REFLEXIVO",
            decisive: "DECISIVO",
            analytical: "ANALÍTICO",
            urgent: "URGENTE",
            strategic: "ESTRATÉGICO",
            operational: "OPERACIONAL",
            low: "INTENSIDAD BAJA",
            medium: "INTENSIDAD MEDIA",
            high: "INTENSIDAD ALTA"
        },
        messages: {
            processing: "TRANSMUTANDO...",
            uploading: "Subiendo audio...",
            transcribing: "Transcribiendo voz...",
            extracting: "Extrayendo ideas clave...",
            formatting: "Formateando estrategia...",
            mic_error: "Se requiere acceso al micrófono.",
            draft_saved: "¡Guardado en borradores!",
            copy_success: "Enlace copiado al portapapeles",
            share_text: "Estoy usando GhostNote Pro para transmutar mis pensamientos. Pruébalo aquí:",
            ready: "Listo para convertir el ruido en señal.",
            tap_record: "Toca para grabar",
            tap_finish: "Toca para terminar",
            free_limit: "Transmutaciones gratuitas completas. Mejore a Pro",
            powered_by: "Impulsado por GhostNote Pro",
            generated_on: "Generado el",
            create_own: "Crea tu propio informe estratégico",
            archive_success: "Informe archivado. Enlace copiado.",
            archive_fail: "Error al archivar."
        },
        legal: {
            privacy: "Privacidad",
            terms: "Términos",
            refund: "Política de Reembolso"
        },
        modes: {
            record_desc: "Capture sus pensamientos estratégicos mediante grabación de voz.",
            upload_desc: "Sube un archivo de audio existente para su análisis."
        },
        labels: {
            duration: "Duración",
            intensity: "Intensidad",
            executive_state: "Estado Ejecutivo",
            emphasis_audit: "Auditoría de Énfasis",
            generate_suite: "GENERAR SUITE EJECUTIVA",
            archive_share: "Archivar y Compartir",
            exec_status: "Estado Ejecutivo",
            pro: "Pro",
            standard: "Estándar",
            new_session: "Nueva Sesión"
        },
        wager: {
            lock_title: "Bloqueo de Juicio",
            lock_desc: "No solo espere. Prediga. Bloquee esta decisión en el 'Historial' para probar la precisión de su juicio más tarde.",
            seal_btn: "Sellar Cápsula del Tiempo",
            prediction_lbl: "La Predicción",
            prediction_placeholder: "¿Cuál es el resultado esperado en la realidad?",
            timeline_lbl: "Línea de Tiempo de Auditoría",
            confirm_btn: "Confirmar Bloqueo",
            cancel_btn: "Cancelar",
            sealing: "Sellando...",
            success: "Cápsula Sellada. Juicio bloqueado.",
            fail: "Error al sellar cápsula."
        },
        drafts_view: {
            subtitle: "Ideas crudas. Planes sin eclosionar. Descarga tu cerebro aquí.",
            empty_title: "Aún no hay borradores",
            empty_desc: "Graba un pensamiento y presiona 'Guardar' para almacenarlo aquí."
        },
        history_view: {
            title: "Historial",
            subtitle: "Motor de Variación de Juicio",
            no_wagers: "NO SE ENCONTRARON APUESTAS",
            quote: "\"La decisión no examinada no vale la pena tomarla.\"",
            avg_accuracy: "Precisión Promedio",
            total_wagers: "Total de Apuestas",
            blind_spot: "Punto Ciego",
            insight: "Insight",
            reckoning_title: "El Ajuste de Cuentas",
            reckoning_desc: "Registra lo que realmente sucedió. Gemini calculará la variación.",
            record_update: "Registrar Actualización",
            update_captured: "Actualización Capturada.",
            seal_judgment: "Sellar Juicio",
            running: "Ejecutando Motor de Variación...",
            discard: "Descartar y Regrabar",
            return: "Volver al Historial",
            accuracy_score: "Puntuación de Precisión de Juicio"
        },
        brief_view: {
            retrieving: "Recuperando de la Bóveda...",
            not_found: "Archivo No Encontrado",
            expunged: "Este informe estratégico ha sido eliminado o nunca existió.",
            return_command: "Volver al Comando",
            archive_label: "Archivo GhostNote Pro",
            create_own: "Crea tu propio informe",
            duration: "DURACIÓN",
            intensity: "INTENSIDAD",
            state: "Estado",
            generated_by: "Este informe estratégico fue generado por GhostNote Pro."
        },
        museum: {
            header_reader: "LECTOR",
            try_free: "Prueba Gratis",
            memo_label: "Nota Estratégica",
            internal_access: "Acceso Interno Solamente",
            encrypted: "Inteligencia Encriptada",
            lock_title: "Auditoría de Riesgo Ejecutiva y Borradores Privados",
            lock_desc: "Esta inteligencia es privada del autor. Genere su propia suite estratégica para desbloquear auditores de riesgo y activos de ejecución.",
            built_for: "Construido para el ejecutivo moderno.",
            opening: "Abriendo los archivos..."
        },
        paywall: {
            headline: "Sigue convirtiendo el pensamiento en estrategia",
            subtext: "Pro elimina los límites diarios y desbloquea la transmutación de nivel ejecutivo, el análisis de confianza y los resultados compartibles.",
            cancel: "Cancela en cualquier momento. Sin tarifas ocultas.",
            restore: "Restaurar compra",
            button_usd: "Continuar con la membresía — $20/mes",
            button_ngn: "Continuar con la membresía — ₦30,000/mes",
            payment_error: "El sistema de pago no está disponible temporalmente. Inténtalo de nuevo.",
            verification_failed: "Verificación fallida",
            network_error: "La verificación falló debido a un error de red.",
            gateway_error: "No se pudo abrir la pasarela de pago. Por favor actualice."
        }
    },
    DE: {
        hero: {
            title: "Verwandeln Sie Chaos in ",
            titleHighlight: "Strategie.",
            subtitle: "Die private Engine zur Transmutation von Führungskräfte-Sprachnotizen in eine strategische Suite.",
            footer: "Kein Tippen. Keine Halluzinationen. Nur Ihre Absicht, kristallisiert.",
        },
        navigation: {
            drafts: "ENTWÜRFE",
            history: "VERLAUF",
            new: "NEUE SITZUNG",
            signin: "ANMELDEN"
        },
        buttons: {
            record: "Aufnehmen",
            upload: "Hochladen",
            transmute: "Gedanken transmutieren",
            save_draft: "Entwurf speichern",
            discard: "Verwerfen",
            rerecord: "Neu aufnehmen",
            remove: "Entfernen",
            copy: "KOPIEREN",
            share: "TEILEN",
            email: "PER E-MAIL SENDEN",
            regenerate: "REGENERIEREN",
            gift: "GHOSTNOTE PRO VERSCHENKEN",
            upgrade: "AUF PRO UPGRADEN",
            select_file: "Datei auswählen",
        },
        scribe: {
            title: "DER SCHREIBER",
            description: "Ihre rohen Gedanken, kristallisiert in eine These auf Wall Street Journal-Niveau.",
            core_thesis: "KERNTHESE",
            strategic_pillars: "STRATEGISCHE SÄULEN",
            transcription: "TRANSKRIPTION",
            tactical_steps: "TAKISCHE SCHRITTE"
        },
        strategist: {
            title: "DER STRATEGE",
            description: "KI-Stabschef-Intelligenz. Urteilsvermögen. Risikoprüfungen. Ausführungsbereite E-Mails.",
            judgment: "EXEKUTIVES URTEIL",
            risk_audit: "RISIKOPRÜFUNG",
            email_draft: "E-MAIL-ENTWURF",
            unlock_title: "Den Strategen freischalten",
            unlock_desc: "Holen Sie sich die komplette Stabschef-Suite: Exekutives Urteil, Risikoprüfungen und versandfertige E-Mails.",
            operationalize: "DIESE STRATEGIE OPERATIONALISIEREN"
        },
        status: {
            reflective: "REFLEKTIEREND",
            decisive: "ENTSCHLOSSEN",
            analytical: "ANALYTISCH",
            urgent: "DRINGEND",
            strategic: "STRATEGISCH",
            operational: "OPERATIV",
            low: "NIEDRIGE INTENSITÄT",
            medium: "MITTLERE INTENSITÄT",
            high: "HOHE INTENSITÄT"
        },
        messages: {
            processing: "TRANSMUTIERE...",
            uploading: "Audio wird hochgeladen...",
            transcribing: "Stimme wird transkribiert...",
            extracting: "Kernkenntnisse werden extrahiert...",
            formatting: "Strategie wird formatiert...",
            mic_error: "Mikrofonzugriff erforderlich.",
            draft_saved: "In Entwürfen gespeichert!",
            copy_success: "Link in die Zwischenablage kopiert",
            share_text: "Ich benutze GhostNote Pro, um meine Gedanken zu transmutieren. Probieren Sie es hier aus:",
            ready: "Bereit, Rauschen in Signale zu verwandeln.",
            tap_record: "Zum Aufnehmen tippen",
            tap_finish: "Zum Beenden tippen",
            free_limit: "Kostenlose Transmutationen aufgebraucht. Upgrade auf Pro",
            powered_by: "Unterstützt von GhostNote Pro",
            generated_on: "Generiert am",
            create_own: "Erstellen Sie Ihren eigenen Strategiebrief",
            archive_success: "Brief archiviert. Link kopiert.",
            archive_fail: "Archivierung fehlgeschlagen."
        },
        legal: {
            privacy: "Datenschutz",
            terms: "AGB",
            refund: "Rückerstattung"
        },
        modes: {
            record_desc: "Erfassen Sie Ihre strategischen Gedanken per Sprachaufzeichnung.",
            upload_desc: "Laden Sie eine vorhandene Audiodatei zur Analyse hoch."
        },
        labels: {
            duration: "Dauer",
            intensity: "Intensität",
            executive_state: "Führungszustand",
            emphasis_audit: "Schwerpunktsaudit",
            generate_suite: "EXEKUTIV-SUITE GENERIEREN",
            archive_share: "Archivieren & Teilen",
            exec_status: "Führungsstatus",
            pro: "Pro",
            standard: "Standard",
            new_session: "Neue Sitzung"
        },
        wager: {
            lock_title: "Urteilsverriegelung",
            lock_desc: "Hoffen Sie nicht nur. Sagen Sie voraus. Sperren Sie diese Entscheidung in den 'Verlauf', um Ihre Urteilsgenauigkeit später zu testen.",
            seal_btn: "Zeitkapsel versiegeln",
            prediction_lbl: "Die Vorhersage",
            prediction_placeholder: "Was ist das erwartete Ergebnis in der Realität?",
            timeline_lbl: "Audit-Zeitplan",
            confirm_btn: "Urteilsverriegelung bestätigen",
            cancel_btn: "Abbrechen",
            sealing: "Versiegelung...",
            success: "Zeitkapsel versiegelt. Urteil gesperrt.",
            fail: "Versiegelung fehlgeschlagen."
        },
        drafts_view: {
            subtitle: "Rohe Ideen. Unausgegorene Pläne. Entladen Sie hier Ihr Gehirn.",
            empty_title: "Noch keine Entwürfe",
            empty_desc: "Nehmen Sie einen Gedanken auf und drücken Sie 'Speichern', um ihn hier zu sichern."
        },
        history_view: {
            title: "Verlauf",
            subtitle: "Urteilsvarianz-Engine",
            no_wagers: "KEINE WETTEN GEFUNDEN",
            quote: "\"Das ungeprüfte Leben ist nicht lebenswert.\"",
            avg_accuracy: "Durchschn. Genauigkeit",
            total_wagers: "Wetten Gesamt",
            blind_spot: "Blinder Fleck",
            insight: "Erkenntnis",
            reckoning_title: "Die Abrechnung",
            reckoning_desc: "Erfassen Sie, was wirklich passiert ist. Gemini berechnet die Varianz.",
            record_update: "Update aufzeichnen",
            update_captured: "Update erfasst.",
            seal_judgment: "Urteil besiegeln",
            running: "Varianz-Engine läuft...",
            discard: "Verwerfen und neu aufnehmen",
            return: "Zurück zum Verlauf",
            accuracy_score: "Urteilsgenauigkeits-Score"
        },
        brief_view: {
            retrieving: "Abruf aus dem Tresor...",
            not_found: "Archiv nicht gefunden",
            expunged: "Dieser Strategiebrief wurde gelöscht oder existierte nie.",
            return_command: "Zurück zum Kommando",
            archive_label: "GhostNote Pro Archiv",
            create_own: "Erstellen Sie Ihren eigenen Brief",
            duration: "DAUER",
            intensity: "INTENSITÄT",
            state: "Status",
            generated_by: "Dieser Strategiebrief wurde von GhostNote Pro erstellt."
        },
        museum: {
            header_reader: "LESER",
            try_free: "Kostenlos Testen",
            memo_label: "Strategisches Memo",
            internal_access: "Nur interner Zugriff",
            encrypted: "Verschlüsselte Intelligenz",
            lock_title: "Exekutive Risikoprüfung & Private Entwürfe",
            lock_desc: "Diese Intelligenz ist privat für den Autor. Generieren Sie Ihre eigene strategische Suite, um Risikoprüfer und Ausführungsressourcen freizuschalten.",
            built_for: "Gebaut für die moderne Führungskraft.",
            opening: "Öffne die Archive..."
        },
        paywall: {
            headline: "Verwandeln Sie weiterhin Gedanken in Strategie",
            subtext: "Pro entfernt tägliche Limits und schaltet die Transmutation auf Führungsebene, Vertrauensanalyse und teilbare Ergebnisse frei.",
            cancel: "Jederzeit kündbar. Keine versteckten Gebühren.",
            restore: "Kauf wiederherstellen",
            button_usd: "Mitgliedschaft fortsetzen – 20 $/Monat",
            button_ngn: "Mitgliedschaft fortsetzen – 30.000 ₦/Monat",
            payment_error: "Zahlungssystem vorübergehend nicht verfügbar. Bitte versuchen Sie es erneut.",
            verification_failed: "Verifizierung fehlgeschlagen",
            network_error: "Verifizierung aufgrund eines Netzwerkfehlers fehlgeschlagen.",
            gateway_error: "Zahlungsgateway konnte nicht geöffnet werden. Bitte aktualisieren."
        }
    },
    ZH: {
        hero: {
            title: "将混乱转化为 ",
            titleHighlight: "战略。",
            subtitle: "将高管语音笔记转化为战略套件的私人引擎。",
            footer: "无需打字。没有幻觉。只有您的意图，经过结晶。",
        },
        navigation: {
            drafts: "草稿",
            history: "历史",
            new: "新会话",
            signin: "登录"
        },
        buttons: {
            record: "录制",
            upload: "上传",
            transmute: "转化我的想法",
            save_draft: "保存草稿",
            discard: "丢弃",
            rerecord: "重新录制",
            remove: "移除",
            copy: "复制",
            share: "分享",
            email: "发送邮件",
            regenerate: "重新生成",
            gift: "赠送 GHOSTNOTE PRO",
            upgrade: "升级到 PRO",
            select_file: "选择文件",
        },
        scribe: {
            title: "书记员",
            description: "您的原始想法，结晶为《华尔街日报》级别的论点。",
            core_thesis: "核心论点",
            strategic_pillars: "战略支柱",
            transcription: "转录",
            tactical_steps: "战术步骤"
        },
        strategist: {
            title: "战略家",
            description: "AI 幕僚长智能。判断。风险审计。可执行邮件。",
            judgment: "执行判断",
            risk_audit: "风险审计",
            email_draft: "邮件草稿",
            unlock_title: "解锁战略家",
            unlock_desc: "获取完整的幕僚长套件：执行判断、风险审计和可发送的邮件。",
            operationalize: "实施此战略"
        },
        status: {
            reflective: "反思性",
            decisive: "果断",
            analytical: "分析性",
            urgent: "紧急",
            strategic: "战略性",
            operational: "操作性",
            low: "低强度",
            medium: "中等强度",
            high: "高强度"
        },
        messages: {
            processing: "转化中...",
            uploading: "正在上传音频...",
            transcribing: "正在转录语音...",
            extracting: "正在提取核心见解...",
            formatting: "正在格式化战略...",
            mic_error: "需要麦克风权限。",
            draft_saved: "已保存到草稿！",
            copy_success: "链接已复制到剪贴板",
            share_text: "我正在使用 GhostNote Pro 转化我的想法。在这里试用：",
            ready: "准备将噪音转化为信号。",
            tap_record: "点击录制",
            tap_finish: "点击完成",
            free_limit: "免费转化已用完。升级到 Pro",
            powered_by: "由 GhostNote Pro 提供支持",
            generated_on: "生成于",
            create_own: "创建您自己的战略简报",
            archive_success: "简报已存档。链接已复制。",
            archive_fail: "存档失败。"
        },
        legal: {
            privacy: "隐私",
            terms: "条款",
            refund: "退款政策"
        },
        modes: {
            record_desc: "通过录音捕捉您的战略构想。",
            upload_desc: "上传现有的音频文件进行分析。"
        },
        labels: {
            duration: "持续时间",
            intensity: "强度",
            executive_state: "执行状态",
            emphasis_audit: "重点审计",
            generate_suite: "生成执行套件",
            archive_share: "存档并分享简报",
            exec_status: "执行状态",
            pro: "Pro",
            standard: "标准",
            new_session: "新会话"
        },
        wager: {
            lock_title: "判断锁定",
            lock_desc: "不要只是希望。预测。将此决定锁定到“历史”中，以便稍后测试您的判断准确性。",
            seal_btn: "密封时间胶囊",
            prediction_lbl: "预测",
            prediction_placeholder: "现实中的预期结果是什么？",
            timeline_lbl: "审计时间表",
            confirm_btn: "确认判断锁定",
            cancel_btn: "取消",
            sealing: "正在密封...",
            success: "时间胶囊已密封。判断已锁定。",
            fail: "密封失败。"
        },
        drafts_view: {
            subtitle: "原始想法。未孵化的计划。在此倾倒您的大脑。",
            empty_title: "暂无草稿",
            empty_desc: "录制一个想法并点击“保存草稿”将其保存在此处。"
        },
        history_view: {
            title: "历史",
            subtitle: "判断差异引擎",
            no_wagers: "未找到任何赌注",
            quote: "\"未经审视的决定不值得做。\"",
            avg_accuracy: "平均准确率",
            total_wagers: "总赌注",
            blind_spot: "盲点",
            insight: "见解",
            reckoning_title: "清算",
            reckoning_desc: "记录实际发生的情况。Gemini 将计算差异。",
            record_update: "记录更新",
            update_captured: "更新已捕获。",
            seal_judgment: "密封判断",
            running: "正在运行差异引擎...",
            discard: "丢弃并重新录制",
            return: "返回历史",
            accuracy_score: "判断准确率得分"
        },
        brief_view: {
            retrieving: "正在从保险库检索...",
            not_found: "未找到档案",
            expunged: "此战略简报已被删除或从未存在。",
            return_command: "返回指挥部",
            archive_label: "GhostNote Pro 档案",
            create_own: "创建您自己的简报",
            duration: "持续时间",
            intensity: "强度",
            state: "状态",
            generated_by: "此战略简报由 GhostNote Pro 生成。"
        },
        museum: {
            header_reader: "读者",
            try_free: "免费试用",
            memo_label: "战略备忘录",
            internal_access: "仅限内部访问",
            encrypted: "加密情报",
            lock_title: "执行风险审计和私人草稿",
            lock_desc: "此情报归作者私有。生成您自己的战略套件以解锁风险审计和执行资产。",
            built_for: "专为现代高管打造。",
            opening: "正在打开档案..."
        },
        paywall: {
            headline: "继续将思想转化为战略",
            subtext: "Pro 取消每日限制并解锁高管级转化、置信度分析和可共享的输出。",
            cancel: "随时取消。无隐藏费用。",
            restore: "恢复购买",
            button_usd: "继续会员资格 — $20/月",
            button_ngn: "继续会员资格 — ₦30,000/月",
            payment_error: "支付系统暂时不可用。请重试。",
            verification_failed: "验证失败",
            network_error: "由于网络错误，验证失败。",
            gateway_error: "无法打开支付网关。请刷新。"
        }
    },
    RU: {
        hero: {
            title: "Превратите Хаос в ",
            titleHighlight: "Стратегию.",
            subtitle: "Приватный двигатель для трансмутации голосовых заметок руководителей в стратегический пакет.",
            footer: "Без печати. Без галлюцинаций. Только ваше намерение, кристаллизованное.",
        },
        navigation: {
            drafts: "ЧЕРНОВИКИ",
            history: "ИСТОРИЯ",
            new: "НОВАЯ СЕССИЯ",
            signin: "ВОЙТИ"
        },
        buttons: {
            record: "Запись",
            upload: "Загрузить",
            transmute: "Трансмутировать мысли",
            save_draft: "Сохранить",
            discard: "Сбросить",
            rerecord: "Перезаписать",
            remove: "Удалить",
            copy: "КОПИРОВАТЬ",
            share: "ПОДЕЛИТЬСЯ",
            email: "ОТПРАВИТЬ EMAIL",
            regenerate: "СГЕНЕРИРОВАТЬ СНОВА",
            gift: "ПОДАРИТЬ GHOSTNOTE PRO",
            upgrade: "ОБНОВИТЬ ДО PRO",
            select_file: "Выбрать файл",
        },
        scribe: {
            title: "ПИСАРЬ",
            description: "Ваши сырые мысли, кристаллизованные в тезис уровня Wall Street Journal.",
            core_thesis: "ГЛАВНЫЙ ТЕЗИС",
            strategic_pillars: "СТРАТЕГИЧЕСКИЕ СТОЛПЫ",
            transcription: "ТРАНСКРИПЦИЯ",
            tactical_steps: "ТАКТИЧЕСКИЕ ШАГИ"
        },
        strategist: {
            title: "СТРАТЕГ",
            description: "Интеллект ИИ-начальника штаба. Суждение. Аудит рисков. Готовые к исполнению письма.",
            judgment: "ИСПОЛНИТЕЛЬНОЕ СУЖДЕНИЕ",
            risk_audit: "АУДИТ РИСКОВ",
            email_draft: "ЧЕРНОВИК ПИСЬМА",
            unlock_title: "Разблокировать Стратега",
            unlock_desc: "Получите полный набор Начальника штаба: Исполнительное суждение, Аудит рисков и готовые к отправке письма.",
            operationalize: "ВНЕДРИТЬ ЭТУ СТРАТЕГИЮ"
        },
        status: {
            reflective: "РЕФЛЕКСИВНЫЙ",
            decisive: "РЕШИТЕЛЬНЫЙ",
            analytical: "АНАЛИТИЧЕСКИЙ",
            urgent: "СРОЧНЫЙ",
            strategic: "СТРАТЕГИЧЕСКИЙ",
            operational: "ОПЕРАЦИОННЫЙ",
            low: "НИЗКАЯ ИНТЕНСИВНОСТЬ",
            medium: "СРЕДНЯЯ ИНТЕНСИВНОСТЬ",
            high: "ВЫСОКАЯ ИНТЕНСИВНОСТЬ"
        },
        messages: {
            processing: "ТРАНСМУТАЦИЯ...",
            uploading: "Загрузка аудио...",
            transcribing: "Транскрибация голоса...",
            extracting: "Извлечение ключевых инсайтов...",
            formatting: "Форматирование стратегии...",
            mic_error: "Требуется доступ к микрофону.",
            draft_saved: "Сохранено в черновики!",
            copy_success: "Ссылка скопирована в буфер обмена",
            share_text: "Я использую GhostNote Pro для трансмутации своих мыслей. Попробуйте здесь:",
            ready: "Готов превратить шум в сигнал.",
            tap_record: "Нажмите для записи",
            tap_finish: "Нажмите для завершения",
            free_limit: "Бесплатные трансмутации исчерпаны. Обновитесь до Pro",
            powered_by: "При поддержке GhostNote Pro",
            generated_on: "Сгенерировано",
            create_own: "Создайте свой стратегический бриф",
            archive_success: "Бриф архивирован. Ссылка скопирована.",
            archive_fail: "Ошибка архивации."
        },
        legal: {
            privacy: "Конфиденциальность",
            terms: "Условия",
            refund: "Возврат средств"
        },
        modes: {
            record_desc: "Запишите свои стратегические мысли через голосовую запись.",
            upload_desc: "Загрузите существующий аудиофайл для анализа."
        },
        labels: {
            duration: "Длительность",
            intensity: "Интенсивность",
            executive_state: "Исполнительное состояние",
            emphasis_audit: "Аудит акцентов",
            generate_suite: "СГЕНЕРИРОВАТЬ ПАКЕТ",
            archive_share: "Архивировать и поделиться",
            exec_status: "Статус",
            pro: "Pro",
            standard: "Стандарт",
            new_session: "Новая сессия"
        },
        wager: {
            lock_title: "Блокировка Суждения",
            lock_desc: "Не просто надейтесь. Предсказывайте. Зафиксируйте это решение в 'Истории', чтобы проверить точность вашего суждения позже.",
            seal_btn: "Запечатать капсулу времени",
            prediction_lbl: "Предсказание",
            prediction_placeholder: "Каков ожидаемый результат в реальности?",
            timeline_lbl: "График аудита",
            confirm_btn: "Подтвердить блокировку",
            cancel_btn: "Отмена",
            sealing: "Запечатывание...",
            success: "Капсула запечатана. Суждение заблокировано.",
            fail: "Не удалось запечатать."
        },
        drafts_view: {
            subtitle: "Сырые идеи. Невынашенные планы. Разгрузите свой мозг здесь.",
            empty_title: "Пока нет черновиков",
            empty_desc: "Запишите мысль и нажмите 'Сохранить', чтобы оставить её здесь."
        },
        history_view: {
            title: "История",
            subtitle: "Двигатель Вариации Суждений",
            no_wagers: "СТАВКИ НЕ НАЙДЕНЫ",
            quote: "\"Неисследованное решение не стоит принимать.\"",
            avg_accuracy: "Ср. точность",
            total_wagers: "Всего ставок",
            blind_spot: "Слепое пятно",
            insight: "Инсайт",
            reckoning_title: "Расплата",
            reckoning_desc: "Запишите, что произошло на самом деле. Gemini рассчитает отклонение.",
            record_update: "Записать обновление",
            update_captured: "Обновление захвачено.",
            seal_judgment: "Запечатать Суждение",
            running: "Запуск двигателя вариации...",
            discard: "Сбросить и перезаписать",
            return: "Вернуться в Историю",
            accuracy_score: "Оценка Точности Суждения"
        },
        brief_view: {
            retrieving: "Извлечение из Хранилища...",
            not_found: "Архив не найден",
            expunged: "Этот стратегический бриф был удален или никогда не существовал.",
            return_command: "Вернуться к Команде",
            archive_label: "Архив GhostNote Pro",
            create_own: "Создайте свой бриф",
            duration: "ДЛИТЕЛЬНОСТЬ",
            intensity: "ИНТЕНСИВНОСТЬ",
            state: "Состояние",
            generated_by: "Этот стратегический бриф был сгенерирован GhostNote Pro."
        },
        museum: {
            header_reader: "ЧИТАТЕЛЬ",
            try_free: "Попробовать бесплатно",
            memo_label: "Стратегическая заметка",
            internal_access: "Только внутренний доступ",
            encrypted: "Зашифрованная разведка",
            lock_title: "Исполнительный аудит рисков и частные черновики",
            lock_desc: "Эта информация является частной для автора. Создайте свой собственный стратегический пакет, чтобы разблокировать аудиторов рисков и активы исполнения.",
            built_for: "Создано для современного руководителя.",
            opening: "Открытие архивов..."
        },
        paywall: {
            headline: "Продолжайте превращать мысли в стратегию",
            subtext: "Pro снимает дневные лимиты и разблокирует трансмутацию исполнительного уровня, анализ уверенности и результаты, которыми можно поделиться.",
            cancel: "Отмена в любое время. Никаких скрытых платежей.",
            restore: "Восстановить покупку",
            button_usd: "Продлить подписку — $20/мес",
            button_ngn: "Продлить подписку — ₦30,000/мес",
            payment_error: "Платежная система временно недоступна. Пожалуйста, попробуйте еще раз.",
            verification_failed: "Ошибка проверки",
            network_error: "Проверка не удалась из-за ошибки сети.",
            gateway_error: "Не удалось открыть платежный шлюз. Пожалуйста, обновите страницу."
        }
    },
    JA: {
        hero: {
            title: "混沌を",
            titleHighlight: "戦略に変える。",
            subtitle: "経営者の音声メモを戦略的スイートに変換するためのプライベートエンジン。",
            footer: "入力不要。幻覚なし。あなたの意図だけを結晶化。",
        },
        navigation: {
            drafts: "下書き",
            history: "履歴",
            new: "新しいセッション",
            signin: "サインイン"
        },
        buttons: {
            record: "録音",
            upload: "アップロード",
            transmute: "思考を変換する",
            save_draft: "下書きを保存",
            discard: "破棄",
            rerecord: "再録音",
            remove: "削除",
            copy: "コピー",
            share: "共有",
            email: "メールで送信",
            regenerate: "再生成",
            gift: "GHOSTNOTE PROを贈る",
            upgrade: "PROにアップグレード",
            select_file: "ファイルを選択",
        },
        scribe: {
            title: "書記官",
            description: "あなたの生の思考を、ウォール・ストリート・ジャーナル品質の論文に結晶化します。",
            core_thesis: "核心的提言",
            strategic_pillars: "戦略的柱",
            transcription: "文字起こし",
            tactical_steps: "戦術的ステップ"
        },
        strategist: {
            title: "戦略家",
            description: "AI参謀長インテリジェンス。判断。リスク監査。実行可能なメール。",
            judgment: "経営判断",
            risk_audit: "リスク監査",
            email_draft: "メール下書き",
            unlock_title: "戦略家を解除",
            unlock_desc: "完全な参謀長スイートを取得：経営判断、リスク監査、送信可能なメール。",
            operationalize: "この戦略を実行に移す"
        },
        status: {
            reflective: "内省的",
            decisive: "断固たる",
            analytical: "分析的",
            urgent: "緊急",
            strategic: "戦略的",
            operational: "運用的",
            low: "低強度",
            medium: "中強度",
            high: "高強度"
        },
        messages: {
            processing: "変換中...",
            uploading: "音声をアップロード中...",
            transcribing: "音声を文字起こし中...",
            extracting: "核心的洞察を抽出中...",
            formatting: "戦略をフォーマット中...",
            mic_error: "マイクへのアクセスが必要です。",
            draft_saved: "下書きに保存しました！",
            copy_success: "リンクをクリップボードにコピーしました",
            share_text: "GhostNote Proを使って思考を変換しています。こちらで試してみてください：",
            ready: "ノイズをシグナルに変える準備ができました。",
            tap_record: "タップして録音",
            tap_finish: "タップして終了",
            free_limit: "無料変換を使い切りました。Proにアップグレード",
            powered_by: "Powered by GhostNote Pro",
            generated_on: "生成日",
            create_own: "独自の戦略概要を作成",
            archive_success: "概要をアーカイブしました。リンクをコピーしました。",
            archive_fail: "アーカイブに失敗しました。"
        },
        legal: {
            privacy: "プライバシー",
            terms: "利用規約",
            refund: "返金ポリシー"
        },
        modes: {
            record_desc: "音声録音で戦略的な思考を記録します。",
            upload_desc: "分析のために既存のオーディオファイルをアップロードします。"
        },
        labels: {
            duration: "期間",
            intensity: "強度",
            executive_state: "経営状態",
            emphasis_audit: "重点監査",
            generate_suite: "経営スイートを生成",
            archive_share: "アーカイブして共有",
            exec_status: "経営ステータス",
            pro: "Pro",
            standard: "標準",
            new_session: "新しいセッション"
        },
        wager: {
            lock_title: "判断のロック",
            lock_desc: "ただ願うのではなく、予測してください。この決定を「履歴」にロックして、後で判断の正確さをテストします。",
            seal_btn: "タイムカプセルを封印",
            prediction_lbl: "予測",
            prediction_placeholder: "現実での期待される結果は何ですか？",
            timeline_lbl: "監査タイムライン",
            confirm_btn: "判断ロックを確認",
            cancel_btn: "キャンセル",
            sealing: "封印中...",
            success: "タイムカプセルが封印されました。判断がロックされました。",
            fail: "封印に失敗しました。"
        },
        drafts_view: {
            subtitle: "生のアイデア。未孵化の計画。ここに脳をダンプしてください。",
            empty_title: "ドラフトはまだありません",
            empty_desc: "思考を記録し、「ドラフトを保存」を押してここに保存します。"
        },
        history_view: {
            title: "履歴",
            subtitle: "判断分散エンジン",
            no_wagers: "賭けは見つかりませんでした",
            quote: "\"検討されていない決定は行う価値がありません。\"",
            avg_accuracy: "平均精度",
            total_wagers: "合計賭け数",
            blind_spot: "盲点",
            insight: "洞察",
            reckoning_title: "決算",
            reckoning_desc: "実際に何が起こったかを記録します。Geminiが分散を計算します。",
            record_update: "更新を記録",
            update_captured: "更新がキャプチャされました。",
            seal_judgment: "判断を封印",
            running: "分散エンジンを実行中...",
            discard: "破棄して再録音",
            return: "履歴に戻る",
            accuracy_score: "判断精度スコア"
        },
        brief_view: {
            retrieving: "保管庫から取得中...",
            not_found: "アーカイブが見つかりません",
            expunged: "この戦略的概要は削除されたか、存在しません。",
            return_command: "コマンドに戻る",
            archive_label: "GhostNote Pro アーカイブ",
            create_own: "独自の概要を作成",
            duration: "期間",
            intensity: "強度",
            state: "状態",
            generated_by: "この戦略的概要はGhostNote Proによって生成されました。"
        },
        museum: {
            header_reader: "リーダー",
            try_free: "無料で試す",
            memo_label: "戦略メモ",
            internal_access: "内部アクセスのみ",
            encrypted: "暗号化されたインテリジェンス",
            lock_title: "役員リスク監査と非公開ドラフト",
            lock_desc: "このインテリジェンスは著者の非公開情報です。独自のリスク監査と実行資産を解除するには、独自の戦略スイートを生成してください。",
            built_for: "現代の経営者のために構築されました。",
            opening: "アーカイブを開いています..."
        },
        paywall: {
            headline: "思考を戦略に変え続ける",
            subtext: "Proは日次制限を解除し、経営者レベルの変換、信頼性分析、共有可能な出力を解除します。",
            cancel: "いつでもキャンセル可能。隠れた料金はありません。",
            restore: "購入を復元",
            button_usd: "メンバーシップを継続 — $20/月",
            button_ngn: "メンバーシップを継続 — ₦30,000/月",
            payment_error: "決済システムは一時的に利用できません。もう一度お試しください。",
            verification_failed: "確認に失敗しました",
            network_error: "ネットワークエラーのため確認に失敗しました。",
            gateway_error: "決済ゲートウェイを開けませんでした。更新してください。"
        }
    },
    PT: {
        hero: {
            title: "Transforme o Caos em ",
            titleHighlight: "Estratégia.",
            subtitle: "O motor privado para transmutar notas de voz executivas em uma suíte estratégica.",
            footer: "Sem digitação. Sem alucinações. Apenas sua intenção, cristalizada.",
        },
        navigation: {
            drafts: "RASCUNHOS",
            history: "HISTÓRICO",
            new: "NOVA SESSÃO",
            signin: "ENTRAR"
        },
        buttons: {
            record: "Gravar",
            upload: "Carregar",
            transmute: "Transmutar pensamentos",
            save_draft: "Salvar Rascunho",
            discard: "Descartar",
            rerecord: "Regravar",
            remove: "Remover",
            copy: "COPIAR",
            share: "COMPARTILHAR",
            email: "ENVIAR POR EMAIL",
            regenerate: "REGENERAR",
            gift: "PRESENTEIE GHOSTNOTE PRO",
            upgrade: "ATUALIZAR PARA PRO",
            select_file: "Selecionar arquivo",
        },
        scribe: {
            title: "O ESCRIVÃO",
            description: "Seus pensamentos brutos, cristalizados em uma tese do calibre do Wall Street Journal.",
            core_thesis: "TESE CENTRAL",
            strategic_pillars: "PILARES ESTRATÉGICOS",
            transcription: "TRANSCRIÇÃO",
            tactical_steps: "PASSOS TÁTICOS"
        },
        strategist: {
            title: "O ESTRATEGISTA",
            description: "Inteligência de Chefe de Gabinete IA. Julgamento. Auditorias de Risco. Emails prontos para execução.",
            judgment: "JULGAMENTO EXECUTIVO",
            risk_audit: "AUDITORIA DE RISCO",
            email_draft: "RASCUNHO DE EMAIL",
            unlock_title: "Desbloquear O Estrategista",
            unlock_desc: "Obtenha a suíte completa de Chefe de Gabinete: Julgamento Executivo, Auditorias de Risco e Emails prontos para envio.",
            operationalize: "OPERACIONALIZAR ESTA ESTRATÉGIA"
        },
        status: {
            reflective: "REFLEXIVO",
            decisive: "DECISIVO",
            analytical: "ANALÍTICO",
            urgent: "URGENTE",
            strategic: "ESTRATÉGICO",
            operational: "OPERACIONAL",
            low: "BAIXA INTENSIDADE",
            medium: "MÉDIA INTENSIDADE",
            high: "ALTA INTENSIDADE"
        },
        messages: {
            processing: "TRANSMUTANDO...",
            uploading: "Enviando áudio...",
            transcribing: "Transcrevendo voz...",
            extracting: "Extraindo insights principais...",
            formatting: "Formatando estratégia...",
            mic_error: "Acesso ao microfone necessário.",
            draft_saved: "Salvo em Rascunhos!",
            copy_success: "Link copiado para a área de transferência",
            share_text: "Estou usando GhostNote Pro para transmutar meus pensamentos. Experimente aqui:",
            ready: "Pronto para transformar ruído em sinal.",
            tap_record: "Toque para Gravar",
            tap_finish: "Toque para Terminar",
            free_limit: "Transmutações gratuitas completas. Atualize para Pro",
            powered_by: "Desenvolvido por GhostNote Pro",
            generated_on: "Gerado em",
            create_own: "Crie seu próprio resumo estratégico",
            archive_success: "Resumo arquivado. Link copiado.",
            archive_fail: "Falha ao arquivar."
        },
        legal: {
            privacy: "Privacidade",
            terms: "Termos",
            refund: "Política de Reembolso"
        },
        modes: {
            record_desc: "Capture seus pensamentos estratégicos via gravação de voz.",
            upload_desc: "Carregue um arquivo de áudio existente para análise."
        },
        labels: {
            duration: "Duração",
            intensity: "Intensidade",
            executive_state: "Estado Executivo",
            emphasis_audit: "Auditoria de Ênfase",
            generate_suite: "GERAR SUÍTE EXECUTIVA",
            archive_share: "Arquivar e Compartilhar",
            exec_status: "Status Executivo",
            pro: "Pro",
            standard: "Padrão",
            new_session: "Nova Sessão"
        },
        wager: {
            lock_title: "Bloqueio de Julgamento",
            lock_desc: "Não espere apenas. Preveja. Bloqueie esta decisão no 'Histórico' para testar a precisão do seu julgamento mais tarde.",
            seal_btn: "Selar Cápsula do Tempo",
            prediction_lbl: "A Previsão",
            prediction_placeholder: "Qual é o resultado esperado na realidade?",
            timeline_lbl: "Cronograma de Auditoria",
            confirm_btn: "Confirmar Bloqueio",
            cancel_btn: "Cancelar",
            sealing: "Selando...",
            success: "Cápsula Selada. Julgamento bloqueado.",
            fail: "Falha ao selar cápsula."
        },
        drafts_view: {
            subtitle: "Ideias brutas. Planos não chocados. Despeje seu cérebro aqui.",
            empty_title: "Sem rascunhos ainda",
            empty_desc: "Grave um pensamento e clique em 'Salvar Rascunho' para guardá-lo aqui."
        },
        history_view: {
            title: "Histórico",
            subtitle: "Motor de Variância de Julgamento",
            no_wagers: "NENHUMA APOSTA ENCONTRADA",
            quote: "\"A decisão não examinada não vale a pena ser tomada.\"",
            avg_accuracy: "Precisão Média",
            total_wagers: "Total de Apostas",
            blind_spot: "Ponto Cego",
            insight: "Insight",
            reckoning_title: "O Acerto de Contas",
            reckoning_desc: "Registre o que realmente aconteceu. Gemini calculará a variância.",
            record_update: "Registrar Atualização",
            update_captured: "Atualização Capturada.",
            seal_judgment: "Selar Julgamento",
            running: "Executando Motor de Variância...",
            discard: "Descartar e Regravar",
            return: "Voltar ao Histórico",
            accuracy_score: "Pontuação de Precisão de Julgamento"
        },
        brief_view: {
            retrieving: "Recuperando do Cofre...",
            not_found: "Arquivo Não Encontrado",
            expunged: "Este resumo estratégico foi excluído ou nunca existiu.",
            return_command: "Voltar ao Comando",
            archive_label: "Arquivo GhostNote Pro",
            create_own: "Crie seu próprio resumo",
            duration: "DURAÇÃO",
            intensity: "INTENSIDADE",
            state: "Estado",
            generated_by: "Este resumo estratégico foi gerado pelo GhostNote Pro."
        },
        museum: {
            header_reader: "LEITOR",
            try_free: "Experimentar Grátis",
            memo_label: "Memorando Estratégico",
            internal_access: "Apenas Acesso Interno",
            encrypted: "Inteligência Criptografada",
            lock_title: "Auditoria de Risco Executiva e Rascunhos Privados",
            lock_desc: "Esta inteligência é privada ao autor. Gere sua própria suíte estratégica para desbloquear auditores de risco e ativos de execução.",
            built_for: "Construído para o executivo moderno.",
            opening: "Abrindo os arquivos..."
        },
        paywall: {
            headline: "Continue transformando pensamento em estratégia",
            subtext: "Pro remove limites diários e desbloqueia transmutação de nível executivo, análise de confiança e saídas compartilháveis.",
            cancel: "Cancele a qualquer momento. Sem taxas ocultas.",
            restore: "Restaurar Compra",
            button_usd: "Continuar com a assinatura — $20/mês",
            button_ngn: "Continuar com a assinatura — ₦30.000/mês",
            payment_error: "O sistema de pagamento está temporariamente indisponível. Tente novamente.",
            verification_failed: "Falha na verificação",
            network_error: "Falha na verificação devido a erro de rede.",
            gateway_error: "Não foi possível abrir o gateway de pagamento. Atualize."
        }
    },
    AR: {
        hero: {
            title: "حوّل الفوضى إلى ",
            titleHighlight: "استراتيجية.",
            subtitle: "المحرك الخاص لتحويل الملاحظات الصوتية التنفيذية إلى حزمة استراتيجية.",
            footer: "بدون طباعة. بدون هلوسة. فقط نيتك، متبلورة.",
        },
        navigation: {
            drafts: "المسودات",
            history: "السجل",
            new: "جلسة جديدة",
            signin: "تسجيل الدخول"
        },
        buttons: {
            record: "تسجيل",
            upload: "رفع",
            transmute: "تحويل أفكاري",
            save_draft: "حفظ المسودة",
            discard: "تجاهل",
            rerecord: "إعادة التسجيل",
            remove: "إزالة",
            copy: "نسخ",
            share: "مشاركة",
            email: "إرسال بالبريد",
            regenerate: "إعادة التوليد",
            gift: "إهداء GHOSTNOTE PRO",
            upgrade: "الترقية إلى PRO",
            select_file: "اختر ملف",
        },
        scribe: {
            title: "الكاتب",
            description: "أفكارك الخام، متبلورة في أطروحة بمستوى وول ستريت جورنال.",
            core_thesis: "الأطروحة الجوهرية",
            strategic_pillars: "الركائز الاستراتيجية",
            transcription: "التفريغ النصي",
            tactical_steps: "الخطوات التكتيكية"
        },
        strategist: {
            title: "الاستراتيجي",
            description: "ذكاء رئيس الموظفين بالذكاء الاصطناعي. الحكم. تدقيق المخاطر. رسائل بريد إلكتروني جاهزة للتنفيذ.",
            judgment: "الحكم التنفيذي",
            risk_audit: "تدقيق المخاطر",
            email_draft: "مسودة البريد الإلكتروني",
            unlock_title: "فتح الاستراتيجي",
            unlock_desc: "احصل على حزمة رئيس الموظفين الكاملة: الحكم التنفيذي، تدقيق المخاطر، ورسائل بريد إلكتروني جاهزة للإرسال.",
            operationalize: "تفعيل هذه الاستراتيجية"
        },
        status: {
            reflective: "تأملي",
            decisive: "حاسم",
            analytical: "تحليلي",
            urgent: "عاجل",
            strategic: "استراتيجي",
            operational: "تشغيلي",
            low: "كثافة منخفضة",
            medium: "كثافة متوسطة",
            high: "كثافة عالية"
        },
        messages: {
            processing: "جاري التحويل...",
            uploading: "جاري رفع الصوت...",
            transcribing: "جاري تفريغ الصوت...",
            extracting: "جاري استخراج الرؤى الجوهرية...",
            formatting: "جاري تنسيق الاستراتيجية...",
            mic_error: "الميكروفون مطلوب.",
            draft_saved: "تم الحفظ في المسودات!",
            copy_success: "تم نسخ الرابط",
            share_text: "أستخدم GhostNote Pro لتحويل أفكاري. جربه هنا:",
            ready: "جاهز لتحويل الضوضاء إلى إشارة.",
            tap_record: "انقر للتسجيل",
            tap_finish: "انقر للإنهاء",
            free_limit: "اكتملت التحويلات المجانية. قم بالترقية إلى Pro",
            powered_by: "بدعم من GhostNote Pro",
            generated_on: "تم إنشاؤه في",
            create_own: "أنشئ ملخصك الاستراتيجي الخاص",
            archive_success: "تمت أرشفة الملخص. تم نسخ الرابط.",
            archive_fail: "فشل الأرشفة."
        },
        legal: {
            privacy: "الخصوصية",
            terms: "الشروط",
            refund: "سياسة الاسترداد"
        },
        modes: {
            record_desc: "سجل أفكارك الاستراتيجية عبر التسجيل الصوتي.",
            upload_desc: "ارفع ملف صوتي موجود للتحليل."
        },
        labels: {
            duration: "المدة",
            intensity: "الكثافة",
            executive_state: "الحالة التنفيذية",
            emphasis_audit: "تدقيق التركيز",
            generate_suite: "توليد الحزمة التنفيذية",
            archive_share: "أرشفة ومشاركة",
            exec_status: "الحالة التنفيذية",
            pro: "Pro",
            standard: "قياسي",
            new_session: "جلسة جديدة"
        },
        wager: {
            lock_title: "قفل الحكم",
            lock_desc: "لا تأمل فقط. تنبأ. اقفل هذا القرار في 'السجل' لاختبار دقة حكمك لاحقا.",
            seal_btn: "ختم الكبسولة الزمنية",
            prediction_lbl: "التنبؤ",
            prediction_placeholder: "ما هي النتيجة المتوقعة في الواقع؟",
            timeline_lbl: "الجدول الزمني للتدقيق",
            confirm_btn: "تأكيد قفل الحكم",
            cancel_btn: "إلغاء",
            sealing: "جاري الختم...",
            success: "تم ختم الكبسولة الزمنية. تم قفل الحكم.",
            fail: "فشل في ختم الكبسولة."
        },
        drafts_view: {
            subtitle: "أفكار خام. خطط غير مكتملة. أفرغ عقلك هنا.",
            empty_title: "لا توجد مسودات حتى الآن",
            empty_desc: "سجل فكرة واضغط على 'حفظ المسودة' لحفظها هنا."
        },
        history_view: {
            title: "السجل",
            subtitle: "محرك تباين الحكم",
            no_wagers: "لم يتم العثور على رهانات",
            quote: "\"القرار غير المفحوص لا يستحق اتخاذه.\"",
            avg_accuracy: "متوسط الدقة",
            total_wagers: "إجمالي الرهانات",
            blind_spot: "النقطة العمياء",
            insight: "البصيرة",
            reckoning_title: "الحساب",
            reckoning_desc: "سجل ما حدث بالفعل. سيحسب Gemini التباين.",
            record_update: "تسجيل التحديث",
            update_captured: "تم التقاط التحديث.",
            seal_judgment: "ختم الحكم",
            running: "تشغيل محرك التباين...",
            discard: "تجاهل وإعادة التسجيل",
            return: "العودة إلى السجل",
            accuracy_score: "درجة دقة الحكم"
        },
        brief_view: {
            retrieving: "جاري الاسترداد من الخزنة...",
            not_found: "الأرشيف غير موجود",
            expunged: "تم حذف هذا الملخص الاستراتيجي أو لم يكن موجودا من قبل.",
            return_command: "العودة إلى القيادة",
            archive_label: "أرشيف GhostNote Pro",
            create_own: "أنشئ ملخصك الخاص",
            duration: "المدة",
            intensity: "الشدة",
            state: "الحالة",
            generated_by: "تم إنشاء هذا الملخص الاستراتيجي بواسطة GhostNote Pro."
        },
        museum: {
            header_reader: "القارئ",
            try_free: "جرب مجانا",
            memo_label: "مذكرة استراتيجية",
            internal_access: "وصول داخلي فقط",
            encrypted: "استخبارات مشفرة",
            lock_title: "تدقيق المخاطر التنفيذي والمسودات الخاصة",
            lock_desc: "هذه المعلومات خاصة للمؤلف. قم بتوليد حزمتك الاستراتيجية الخاصة لفتح مدققي المخاطر وأصول التنفيذ.",
            built_for: "صمم للمدير التنفيذي الحديث.",
            opening: "جاري فتح الأرشيف..."
        },
        paywall: {
            headline: "استمر في تحويل الفكر إلى استراتيجية",
            subtext: "يزيل Pro الحدود اليومية ويفتح التحويل على المستوى التنفيذي وتحليل الثقة والمخرجات القابلة للمشاركة.",
            cancel: "إلغاء في أي وقت. لا رسوم خفية.",
            restore: "استعادة الشراء",
            button_usd: "متابعة العضوية — 20 دولارًا/شهر",
            button_ngn: "متابعة العضوية — 30,000 نايرا/شهر",
            payment_error: "نظام الدفع غير متاح مؤقتًا. يرجى المحاولة مرة أخرى.",
            verification_failed: "فشل التحقق",
            network_error: "فشل التحقق بسبب خطأ في الشبكة.",
            gateway_error: "تعذر فتح بوابة الدفع. يرجى التحديث."
        }
    },
    HI: {
        hero: {
            title: "अराजकता को बदलें ",
            titleHighlight: "रणनीति में।",
            subtitle: "कार्यकारी वॉयस नोट्स को रणनीतिक सुइट में बदलने के लिए निजी इंजन।",
            footer: "कोई टाइपिंग नहीं। कोई मतिभ्रम नहीं। बस आपका इरादा, स्पष्ट।",
        },
        navigation: {
            drafts: "ड्राफ्ट",
            history: "इतिहास",
            new: "नया सत्र",
            signin: "साइन इन"
        },
        buttons: {
            record: "रिकॉर्ड करें",
            upload: "अपलोड करें",
            transmute: "विचारों को बदलें",
            save_draft: "ड्राफ्ट सहेजें",
            discard: "त्यागें",
            rerecord: "पुनः रिकॉर्ड करें",
            remove: "हटाएं",
            copy: "कॉपी",
            share: "साझा करें",
            email: "ईमेल करें",
            regenerate: "पुनः उत्पन्न करें",
            gift: "GHOSTNOTE PRO उपहार दें",
            upgrade: "PRO में अपग्रेड करें",
            select_file: "फ़ाइल चुनें",
        },
        scribe: {
            title: "लेखक",
            description: "आपके कच्चे विचार, वॉल स्ट्रीट जर्नल कैलिबर थीसिस में स्पष्ट।",
            core_thesis: "मुख्य थीसिस",
            strategic_pillars: "रणनीतिक स्तंभ",
            transcription: "प्रतिलेखन",
            tactical_steps: "सामरिक कदम"
        },
        strategist: {
            title: "रणनीतिकार",
            description: "एआई चीफ ऑफ स्टाफ इंटेलिजेंस। निर्णय। जोखिम ऑडिट। निष्पादन के लिए तैयार ईमेल।",
            judgment: "कार्यकारी निर्णय",
            risk_audit: "जोखिम ऑडिट",
            email_draft: "ईमेल ड्राफ्ट",
            unlock_title: "रणनीतिकार को अनलॉक करें",
            unlock_desc: "पूर्ण चीफ ऑफ स्टाफ सुइट प्राप्त करें: कार्यकारी निर्णय, जोखिम ऑडिट, और भेजने के लिए तैयार ईमेल।",
            operationalize: "इस रणनीति को संचालित करें"
        },
        status: {
            reflective: "चिंतनशील",
            decisive: "निर्णायक",
            analytical: "विश्लेषणात्मक",
            urgent: "तत्काल",
            strategic: "रणनीतिक",
            operational: "परिचालन",
            low: "कम तीव्रता",
            medium: "मध्यम तीव्रता",
            high: "उच्च तीव्रता"
        },
        messages: {
            processing: "परिवर्तन हो रहा है...",
            uploading: "ऑडियो अपलोड हो रहा है...",
            transcribing: "आवाज़ का प्रतिलेखन...",
            extracting: "मुख्य अंतर्दृष्टि निकाल रहा है...",
            formatting: "रणनीति तैयार कर रहा है...",
            mic_error: "माइक्रोफोन एक्सेस आवश्यक है।",
            draft_saved: "ड्राफ्ट में सहेजा गया!",
            copy_success: "लिंक क्लिपबोर्ड पर कॉपी किया गया",
            share_text: "मैं अपने विचारों को बदलने के लिए GhostNote Pro का उपयोग कर रहा हूं। इसे यहाँ आज़माएं:",
            ready: "शोर को संकेत में बदलने के लिए तैयार।",
            tap_record: "रिकॉर्ड करने के लिए टैप करें",
            tap_finish: "समाप्त करने के लिए टैप करें",
            free_limit: "मुफ्त परिवर्तन पूर्ण। Pro में अपग्रेड करें",
            powered_by: "GhostNote Pro द्वारा संचालित",
            generated_on: "पर उत्पन्न",
            create_own: "अपना रणनीतिक संक्षिप्त बनाएँ",
            archive_success: "संक्षिप्त संग्रहीत। लिंक कॉपी किया गया।",
            archive_fail: "संग्रह करने में विफल।"
        },
        legal: {
            privacy: "गोपनीयता",
            terms: "शर्तें",
            refund: "धनवापसी नीति"
        },
        modes: {
            record_desc: "वॉयस रिकॉर्डिंग के माध्यम से अपने रणनीतिक विचारों को कैप्चर करें।",
            upload_desc: "विश्लेषण के लिए एक मौजूदा ऑडियो फ़ाइल अपलोड करें।"
        },
        labels: {
            duration: "अवधि",
            intensity: "तीव्रता",
            executive_state: "कार्यकारी स्थिति",
            emphasis_audit: "जोर ऑडिट",
            generate_suite: "कार्यकारी सुइट उत्पन्न करें",
            archive_share: "संग्रह और साझा करें",
            exec_status: "स्थिति",
            pro: "Pro",
            standard: "मानक",
            new_session: "नया सत्र"
        },
        wager: {
            lock_title: "निर्णय लॉक",
            lock_desc: "बस आशा मत करो। भविष्यवाणी करें। बाद में अपनी निर्णय सटीकता का परीक्षण करने के लिए इस निर्णय को 'इतिहास' में लॉक करें।",
            seal_btn: "टाइम कैप्सूल सील करें",
            prediction_lbl: "भविष्यवाणी",
            prediction_placeholder: "वास्तविकता में अपेक्षित परिणाम क्या है?",
            timeline_lbl: "ऑडिट समयरेखा",
            confirm_btn: "लॉक की पुष्टि करें",
            cancel_btn: "रद्द करें",
            sealing: "सीलिंग...",
            success: "टाइम कैप्सूल सीलबंद। निर्णय लॉक हो गया।",
            fail: "सील करने में विफल।"
        },
        drafts_view: {
            subtitle: "कच्चे विचार। अधूरी योजनाएँ। अपना दिमाग यहाँ खाली करें।",
            empty_title: "अभी तक कोई ड्राफ्ट नहीं",
            empty_desc: "एक विचार रिकॉर्ड करें और इसे यहाँ सहेजने के लिए 'ड्राफ्ट सहेजें' दबाएं।"
        },
        history_view: {
            title: "इतिहास",
            subtitle: "निर्णय विचरण इंजन",
            no_wagers: "कोई दांव नहीं मिला",
            quote: "\"बिना जांचा-परखा निर्णय लेने योग्य नहीं है।\"",
            avg_accuracy: "औसत सटीकता",
            total_wagers: "कुल दांव",
            blind_spot: "अंधा स्थान",
            insight: "अंतर्दृष्टि",
            reckoning_title: "हिसाब किताब",
            reckoning_desc: "रिकॉर्ड करें कि वास्तव में क्या हुआ। जैमिनी विचरण की गणना करेगा।",
            record_update: "अद्यतन रिकॉर्ड करें",
            update_captured: "अद्यतन कैप्चर किया गया।",
            seal_judgment: "निर्णय सील करें",
            running: "विचरण इंजन चल रहा है...",
            discard: "त्यागें और पुनः रिकॉर्ड करें",
            return: "इतिहास पर लौटें",
            accuracy_score: "निर्णय सटीकता स्कोर"
        },
        brief_view: {
            retrieving: "तिजोरी से पुनः प्राप्त किया जा रहा है...",
            not_found: "संग्रह नहीं मिला",
            expunged: "यह रणनीतिक संक्षिप्त हटा दिया गया है या कभी मौजूद नहीं था।",
            return_command: "कमांड पर लौटें",
            archive_label: "GhostNote Pro संग्रह",
            create_own: "अपना संक्षिप्त बनाएं",
            duration: "अवधि",
            intensity: "तीव्रता",
            state: "स्थिति",
            generated_by: "यह रणनीतिक संक्षिप्त GhostNote Pro द्वारा उत्पन्न किया गया था।"
        },
        museum: {
            header_reader: "पाठक",
            try_free: "निःशुल्क प्रयास करें",
            memo_label: "रणनीतिक ज्ञापन",
            internal_access: "केवल आंतरिक पहुंच",
            encrypted: "एन्क्रिप्टेड खुफिया",
            lock_title: "कार्यकारी जोखिम ऑडिट और निजी ड्राफ्ट",
            lock_desc: "यह खुफिया जानकारी लेखक के लिए निजी है। जोखिम ऑडिटर्स और निष्पादन संपत्ति को अनलॉक करने के लिए अपना खुद का रणनीतिक सुइट बनाएं।",
            built_for: "आधुनिक कार्यकारी के लिए निर्मित।",
            opening: "अभिलेखागार खोल रहा है..."
        },
        paywall: {
            headline: "विचार को रणनीति में बदलना जारी रखें",
            subtext: "Pro दैनिक सीमाओं को हटाता है और कार्यकारी-ग्रेड परिवर्तन, विश्वास विश्लेषण और साझा करने योग्य आउटपुट को अनलॉक करता है।",
            cancel: "कभी भी रद्द करें। कोई छिपी हुई फीस नहीं।",
            restore: "खरीद बहाल करें",
            button_usd: "सदस्यता जारी रखें — $20/माह",
            button_ngn: "सदस्यता जारी रखें — ₦30,000/माह",
            payment_error: "भुगतान प्रणाली अस्थायी रूप से अनुपलब्ध है। कृपया पुन: प्रयास करें।",
            verification_failed: "सत्यापन विफल",
            network_error: "नेटवर्क त्रुटि के कारण सत्यापन विफल रहा।",
            gateway_error: "भुगतान गेटवे नहीं खुल सका। कृपया रिफ्रेश करें।"
        }
    }
};
